name: Check policy
on:
  pull_request:
  push:
    branches:
      - main
      - hotfix/*
      - work/check-policy # For development

jobs:
  policy:
    uses: canonical/starflow/.github/workflows/policy.yaml@main
  python-scans:
    name: Security scan
    uses: canonical/starflow/.github/workflows/scan-python.yaml@main
    with:
      packages: python-apt-dev
      requirements-find-args: "! -path '*/docs/tutorial/**' ! -path '*/tests/spread/**' ! -path '*/tests/data/**'"
      osv-extra-args: "--config=source/osv-scanner.toml"
      uv-export: false
