name: Spread (manual - large/flaky)
on:
  pull_request:
    # The 3 default types + "labeled"
    types: [labeled, opened, reopened, synchronize]
  schedule:
    - cron: "0 2 * * 0,3" # run at 2 AM on Sundays and Wednesdays
  workflow_dispatch:

jobs:
  # Decide if the tests should be ran
  predicate:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.eval.outputs.should_run }}
    steps:
      - id: eval
        run: |
          # OR's the three different conditions in which this should run:
          # - This is an actual scheduled run
          # - This is a manually triggered run via the Actions tab
          # - This is a PR with the 'PR: Run Manual Spread' label
          should_run=${{ contains(github.event.pull_request.labels.*.name, 'PR: Run Manual Spread') || contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name) }}
          echo "should_run=$should_run" >> "$GITHUB_OUTPUT"

  snap-build:
    needs: predicate
    if: needs.predicate.outputs.should_run == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # speed up build times by using wheels, when available
      - name: Use wheels
        run: |
          yq e 'del(.parts.charmcraft."build-environment"[] | select(.UV_NO_BINARY == "true"))' -i snap/snapcraft.yaml
      - name: Build snap
        uses: canonical/action-build@v1
        id: rockcraft
      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.rockcraft.outputs.snap }}

  snap-tests:
    needs: [predicate, snap-build]
    if: needs.predicate.outputs.should_run == 'true'
    runs-on: [self-hosted, spread-installed]

    steps:
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout rockcraft
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: Download snap artifact
        uses: actions/download-artifact@v5
        with:
          name: snap
          path: tests

      - name: Run remote-build tests
        env:
          LAUNCHPAD_TOKEN: "${{ secrets.LAUNCHPAD_TOKEN }}"
        run: spread tests/spread/rockcraft/remote-build
      - name: Run large/flaky tests
        id: flaky
        run: spread tests/spread/manual/

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done
